title: schwarzkopfb
tagline: the guy who solves problems from CSS to NoSQL Database Clusters

pages:
  home:
    theme: blue
    content: about
    link: /
    hidden: true
  about:
    theme: blue
    link: /about
  projects:
    theme: purple
    link: /projects
    title: my expertise
  open:
    label: open source
    theme: green
    content: open
    link: /open
  team:
    theme: red
    link: /team
    tagline: hellooo&nbsp;<strong>world</strong>
  contact:
    theme: orange
    link: /contact
  404:
    hidden: true
    theme: '404'
    link: '/404'

footer: >
  Found a typo? 
  <a href="https://github.com/schwarzkopfb/schwarzkopfb.io" target="_blank">
    Please, let me know!
  </a>
  <br/><br/>
  site design and content © 2019 Balázs Schwarzkopf</br>
  source is licensed under <a href="https://opensource.org/licenses/MIT" target="_blank">MIT</a>
